$text = rgb(d4be98)
$error = rgb(ea6962)
$font = terminus

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# ANIMATIONS
animations {
  enabled = false
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Pictures/wallpaper.png
  blur_passes = 1
  blur_size = 5
}

# DATE
label {
  monitor =
  text = cmd[update:1000] date +"%A, %b %d %I:%M %p"
  color = $text
  font_size = 9
  font_family = $font
  position = -21, -17
  halign = right
  valign = top
}

# DATE CONTAINER
shape {
    monitor =
    size = 175, 24
    color = rgba(00000000)
    rounding = 0
    border_size = 1
    border_color = $text

    position = -10, -10
    halign = right
    valign = top
}

# INPUT FIELD
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(00000000)

    outer_color = $text
    check_color= $text
    fail_color= $error

    font_color = $text
    font_family = $font
    fade_on_empty = false
    rounding = 0

    position = 0, 10
    halign = center
    valign = bottom

    failt_timeout = 100
}
